time_tracker.activity.*:
  type: config_entity
  label: 'Time tracker activity'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    description:
      type: text
      label: 'Description'

time_tracker.time_tracker_settings.*.*:
  type: config_entity
  label: 'Time Tracker Settings'
  mapping:
    id:
      type: string
      label: 'ID'
    target_entity_type_id:
      type: string
      label: 'Entity Type ID'
    target_bundle:
      type:  string
      label: 'Bundle'
    active:
      type:  boolean
      label: 'Time Traking enabled'
